### ISSUE TITLE
Using unicode in filenames, causes "Invalid URL" error on upload

### ISSUE THREAD

**Issue by patroza** [cloudinary/pycloudinary#91] opened 2017-03-20 15:40 UTC
Using Django 1.9, Cloudinary 1.7, Python 2.7, trying to upload an image through Admin, causes: "Invalid URL".

Examle filename: Ümlaut.png

The following patch works around it: https://github.com/patroza/pycloudinary/blob/master/cloudinary/forms.py#L132

**Comment by taragano** [comment] 2017-03-24 17:19
Thank you for that @patroza!
Our team will check it out.

**Comment by hakib** [comment] 2017-09-29 09:52
Just encountered that myself. Any progress or workaround on this issue?

Django 1.11, Python 3.5, Cloudinary 1.8.0

**Comment by idobarnoam** [comment] 2017-10-03 09:37
Hi @hakib, 

The request is still on our dev team's queue. There is currently no updated ETA. Once there will be any new insights, we would make sure to update this thread.

**Comment by rubengrill** [comment] 2018-01-12 09:45
Can this issue get more priority? It was reported almost a year ago and there is no progress at all.
It is still an issue in 1.10.0 and please note that it happens in Python 3.x as well, it is not a simple `UnicodeDecodeError` that could be solved by using Python 3 instead of Python 2.

Using a `CloudinaryField` and simply upload a file `überfällig.png` in the admin fails, I really wonder why this bug has been ignored so far.

**Comment by spookylukey** [comment] 2018-03-05 13:17
The same issue exists trying to use the API call like this:

    cloudinary.uploader.upload(file_object, context={'original_filepath': 'überfällig.png'})

You get an error like this:

      File "/home/luke/.virtualenvs/wolfandbadger/lib/python2.7/site-packages/cloudinary/uploader.py", line 36, in upload
        return call_api("upload", params, file=file, **options)
      File "/home/luke/.virtualenvs/wolfandbadger/lib/python2.7/site-packages/cloudinary/uploader.py", line 257, in call_api
        response = _http.request("POST", api_url, param_list, headers, **kw)
      File "/home/luke/.virtualenvs/wolfandbadger/lib/python2.7/site-packages/urllib3/request.py", line 70, in request
        **urlopen_kw)
      File "/home/luke/.virtualenvs/wolfandbadger/lib/python2.7/site-packages/urllib3/request.py", line 148, in request_encode_body
        return self.urlopen(method, url, **extra_kw)
      File "/home/luke/.virtualenvs/wolfandbadger/lib/python2.7/site-packages/urllib3/poolmanager.py", line 321, in urlopen
        response = conn.urlopen(method, u.request_uri, **kw)
      File "/home/luke/.virtualenvs/wolfandbadger/lib/python2.7/site-packages/urllib3/connectionpool.py", line 601, in urlopen
        chunked=chunked)
      File "/home/luke/.virtualenvs/wolfandbadger/lib/python2.7/site-packages/urllib3/connectionpool.py", line 357, in _make_request
        conn.request(method, url, **httplib_request_kw)
      File "/home/luke/.local/lib/python2.7/httplib.py", line 1054, in request
        self._send_request(method, url, body, headers)
      File "/home/luke/.local/lib/python2.7/httplib.py", line 1094, in _send_request
        self.endheaders(body)
      File "/home/luke/.local/lib/python2.7/httplib.py", line 1050, in endheaders
        self._send_output(message_body)
      File "/home/luke/.local/lib/python2.7/httplib.py", line 892, in _send_output

This is a regression - cloudinary 1.4 client library did not have a problem, cloudinary 1.5 does.

**Comment by yakirp** [comment] 2018-03-07 09:51
Hi, 

The request is still on our dev team's queue. 
I believe it will be fixed in the nearest future. 

Once there will be any new insights, we would make sure to update this thread.

**Comment by julienbornstein** [comment] 2018-04-28 01:26
Update @patroza 's patch : 
```
def to_python(self, value):
        value = super(CloudinaryField, self).to_python(value)

        if isinstance(value, cloudinary.CloudinaryResource):
            return value
        elif isinstance(value, UploadedFile):
            value.name = escape_uri_path(value.name)
            return value
        elif value is None:
            return value
        else:
            value = escape_uri_path(value)
            return self.parse_cloudinary_resource(value)
```

**Comment by cloudinaraz** [comment] 2018-04-29 09:16
Hi @julienbornstein,

Thanks for sharing your code.
The request is still in our SDK dev team queue.

Once an official fix is implemented, we will make sure to update the thread.

**Comment by ksonbol** [comment] 2018-08-16 13:47
In addition to @patroza 's patch, I needed to edit the uploader file to get this to work. It may not be perfect but it works for me: https://github.com/ksonbol/pycloudinary/commit/98f56540e1cf571cabd5ea0e12931dd54edeeef6

I hope to see this fixed in the official repo soon!

**Closed** 2018-10-08 11:40 UTC
Labels: bug

**Comment by const-cloudinary** [comment] 2018-10-08 12:48
This issue in caused by urllib3 bug:
#https://github.com/urllib3/urllib3/issues/900
It was handled on the server side. Now filename* parameter is supported by Cloudinary.
Unit test was added to check that it works as expected.
