### ISSUE TITLE
delete fails when public_id has commas (,)

### ISSUE THREAD

**Issue by oppianmatt** [cloudinary/pycloudinary#47] opened 2015-02-12 09:54 UTC
```
In [40]: public_ids
Out[40]: ['blair-castle-caravan-park/Motorhome in foreground, reception building in background']

In [41]: cloudinary.api.delete_resources(public_ids)
Out[41]:
{u'deleted': {u' reception building in background': u'not_found',
  u'blair-castle-caravan-park/Motorhome in foreground': u'not_found'},
 u'partial': False}
```

Seems to try split the comma even though it's already been given a list. Suspect it's on the cloudinary server end.

**Comment by oppianmatt** [comment] 2015-02-12 10:05
replacing it with %2C or with \, doesn't work either

```
In [44]: cloudinary.api.delete_resources([public_id])
Out[44]:
{u'deleted': {u'blair-castle-caravan-park/Motorhome in foreground%2C reception building in background': u'not_found'},
 u'partial': False}
```

**Comment by idobarnoam** [comment] 2019-01-17 14:34
@oppianmatt Thanks for your patience in this.

We could not reproduce this on our end.
Are you still experiencing this?

**Comment by idobarnoam** [comment] 2019-12-25 13:34
Hi @oppianmatt  I'm Closing this issue due to the time elapsed. 

Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.

**Closed by idobarnoam** 2019-12-25 13:34 UTC
Labels: question
