### ISSUE TITLE
cloudinary proxy support

### ISSUE THREAD

**Issue by kucudevelopers** [cloudinary/pycloudinary#183] opened 2019-02-11 12:21 UTC
Am on a free pythonanywhere account. Image uploads were failing and the reason given supposes that it's due to lack of proxy support. Here is part of the error:
```
File "/home/kucudevs/blog/app/home/views.py", line 65, in write_article
    result = cloudinary.uploader.upload(form.post_image.data)
  File "/home/kucudevs/blogvenv/lib/python3.6/site-packages/cloudinary/uploader.py", line 42, in upload
    return call_cacheable_api("upload", params, file=file, **options)
  File "/home/kucudevs/blogvenv/lib/python3.6/site-packages/cloudinary/uploader.py", line 308, in call_cacheable_api
    result = call_api(action, params, http_headers, return_error, unsigned, file, timeout, **options)
  File "/home/kucudevs/blogvenv/lib/python3.6/site-packages/cloudinary/uploader.py", line 371, in call_api
    raise Error("Unexpected error - {0!r}".format(e))
cloudinary.api.Error: Unexpected error - MaxRetryError("HTTPSConnectionPool(host='api.cloudinary.com', port=443): Max retries exceeded with url: /v1_1/ericouma/image/upload (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4bd813cb00>: Failed to establish a new connection: [Errno 111] Connection refused',))",)
```

**Comment by idobarnoam** [comment] 2019-02-21 13:30
Thanks for letting us know @kucudevelopers.
We will take this internally and look into it. 

We will update the thread with any updates.

**Comment by dwelzer** [comment] 2019-09-02 15:44
do you have any update on this? I getting the same problem... looks like proxy setting are not accepted.

my call:

        result_url = cloudinary.uploader.upload(
            file=file_path,
            use_filename=True,
            folder=upload_folder,
            proxy='http://proxy.ww-intern.de:3128'
        )

error:

Unexpected error - MaxRetryError("HTTPSConnectionPool(host='api.cloudinary.com', port=443): Max retries exceeded with url: /v1_1/dpzordjdw/image/upload (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000002BCE6F4F898>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by idobarnoam** [comment] 2019-09-05 09:30
Hi, @DanielW202 this is being looked and actively being worked on.

 We would share additional updates as they occur.

**Comment by wkentdag** [comment] 2019-09-17 22:27
I am getting a similar error for a piece of code that has been untouched for several years and suddenly stopped working on Friday:

```
cloudinary.api.Error: Unexpected error - MaxRetryError('HTTPSConnectionPool(host=\'api.cloudinary.com\', port=443): Max retries exceeded with url: /v1_1/my-account-id-xxx/image/upload (Caused by SSLError(SSLError("bad handshake: Error([(\'SSL routines\', \'tls_process_server_certificate\', \'certificate verify failed\')],)",),))',)
```

The code in question, in two different places, failing with the same error.

First instance, I'm uploading from a valid URL:
```py
import cloudinary 

url = 'https://img.youtube.com/vi/{}/maxresdefault.jpg'.format(id)
cl_upload = cloudinary.uploader.upload(url, folder = 'media/videos/images')
```

Second instance, I'm uploading from a temporary file on `Photo.save`:

```py
class PhotoSerializer(serializers.ModelSerializer):
    image = serializers.SerializerMethodField()

    def get_image(self, obj):
        return cloudinary_url(obj.image.name, format='jpg')[0]
```

I'd love to hear further updates and/or a workaround @idobarnoam, as for now, I'm unable to upload images in my application.

**Comment by wkentdag** [comment] 2019-09-17 22:43
Update: I was able to temporarily work around this issue by patching the [`uploader.py#379`](https://github.com/cloudinary/pycloudinary/blob/master/cloudinary/uploader.py#L379) like so:

```diff
- response = _http.request("POST", api_url, param_list, headers, **kw)
+ response = _http.request("POST", api_url, param_list, headers, verify=False, ssl_verify=False, **kw)
```

Clearly this isn't a viable long-term solution. I'm still trying to understand why this bug arose without updating my library or code... At a minimum, adding the ability to pass `verify=False` from the uploader interface would be nice.

**Comment by idobarnoam** [comment] 2019-10-03 17:53
@kucudevelopers @DanielW202 @wkentdag wanted to let you know that we recently released version 1.18.1 of our sdk which has proxy support.

Let us know if it works for you.

**Comment by yktoo** [comment] 2019-10-31 12:22
I see that proxy is supported for remote uploads, however I believe what @DanielW202 was after is *uploading a local file via a proxy*.

I'm on 1.18.2 and it doesn't work for me either, `cloudinary.uploader.upload()` gets stuck:

```
[...]
  File ".../python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File ".../python3.6/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File ".../python3.6/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File ".../python3.6/site-packages/urllib3/connection.py", line 334, in connect
    conn = self._new_conn()
  File ".../python3.6/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File ".../python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
KeyboardInterrupt
```

**Comment by roeeba** [comment] 2019-10-31 13:42
Hi @yktoo. Can you please let us know how we can reproduce this issue? would you be able to share the code responsible for it? Thanks.

**Comment by yktoo** [comment] 2019-10-31 13:44
Well I guess all you need is to be behind a proxy and try to upload a local file via the usual API call. I used Python API mentioned above.

**Comment by roeeba** [comment] 2019-11-06 12:44
@yktoo, The way to set it up is via the [configuration settings](https://cloudinary.com/documentation/django_integration#configuration). Can you please try and set the `api_proxy` property to your proxy value and let me know if it's working for you?

**Comment by yktoo** [comment] 2019-11-06 13:12
@roeeba Nope.
```python
>>> cloudinary.config(api_proxy='http://x.x.x.x:8080/', cloud_name='yktoo', api_key='...', api_secret='...')
<cloudinary.Config object at 0x7f22e6b480b8>
>>> cloudinary.uploader.upload('sky.jpg')
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dk/.local/lib/python3.6/site-packages/cloudinary/uploader.py", line 46, in upload
    return call_cacheable_api("upload", params, file=file, **options)
  File "/home/dk/.local/lib/python3.6/site-packages/cloudinary/uploader.py", line 314, in call_cacheable_api
    result = call_api(action, params, http_headers, return_error, unsigned, file, timeout, **options)
[...]
  File "/home/dk/.local/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
KeyboardInterrupt
```

Also peculiar that `api_proxy` doesn't seem to be mentioned anywhere in your docs.

**Comment by roeeba** [comment] 2019-11-06 14:20
@yktoo I apologize for my incomplete reply. Note that for using the API proxy option, the configuration needs to be set up before loading `cloudinary` module (I've opened a ticket to our docs team to get this documented). 
If you're using Django, then you can set it as part of CLOUDINARY configuration in your settings.py. Otherwise, you can set up your CLOUDINARY_URL environment variable and add the `api_proxy` value there (i.e., `CLOUDINARY_URL=cloudinary://API_KEY:API_SECRET@cloud_name?api_proxy=http://x.x.x.x:8080`).

**Comment by yktoo** [comment] 2019-11-06 15:04
Yes the trick with `CLOUDINARY_URL=...` did go well, thanks!

I'm not using Django, just pure Python. I wonder why the `cloudinary.config(api_proxy=...)` call didn't work out, isn't it supposed to work like this, too?

**Comment by roeeba** [comment] 2019-11-10 10:52
@yktoo `cloudinary.config()` needs to be called before you import `cloudinary.api` or `cloudinary.uploader` to make it work. You can also set up the `CLOUDINARY_URL` environment variable or `settings.py` in Django.

**Comment by roeeba** [comment] 2020-03-23 08:05
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Closed by roeeba** 2020-03-23 08:05 UTC
Labels: enhancement

**Comment by Shadow-Knight503** [comment] 2021-11-29 13:37
I am having the same isssue 
Please help

**Comment by atdcloud** [comment] 2022-01-20 18:44
the issue is also answered in StackOverflow, cross-referencing. 
https://stackoverflow.com/questions/70153259/cloudinary-image-upload-errpr-in-django-python-while-hosted-in-pythonanywhere

**Comment by tibuch** [comment] 2022-03-04 14:36
Pretty hard to find this solution with `api_proxy`;)

**Comment by Maxiron** [comment] 2022-08-16 02:16
> I am having the same isssue Please help Error at /post/ Unexpected error - MaxRetryError("HTTPSConnectionPool(host='api.cloudinary.com', port=443): Max retries exceeded with url: /v1_1/meme-topia/image/upload (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8d77f41370>: Failed to establish a new connection: [Errno 111] Connection refused'))")

hello how did you solve this issue?

**Comment by epasos573** [comment] 2022-08-16 03:24
The `api_proxy` can be declared either at the OS env (e.g., `export CLOUDINARY_URL=cloudinary://API_KEY:API_SECRET@cloud_name?api_proxy=http://x.x.x.x:8080`) or when initializing the Cloudinary object (i.e., setting configuration parameters globally in your Python application):

```
CLOUDINARY = {
      'cloud_name': 'CLOUD-NAME',  
      'api_key': 'xx',  
      'api_secret': 'xx',
      'api_proxy': 'http://x.x.x.x:8080'
}
```

**Comment by Maxiron** [comment] 2022-08-16 03:41
> The `api_proxy` can be declared either at the OS env (e.g., `export CLOUDINARY_URL=cloudinary://API_KEY:API_SECRET@cloud_name?api_proxy=http://x.x.x.x:8080`) or when initializing the Cloudinary object (i.e., setting configuration parameters globally in your Python application):
> 
> ```
> CLOUDINARY = {
>       'cloud_name': 'CLOUD-NAME',  
>       'api_key': 'xx',  
>       'api_secret': 'xx',
>       'api_proxy': 'http://x.x.x.x:8080'
> }
> ```

will the proxy be my domain name?

**Comment by Maxiron** [comment] 2022-08-16 03:43
> 

and do i have to setup the proxy seperately

**Comment by epasos573** [comment] 2022-08-16 04:48
The 'api.cloudinary.com:443' has now been [whitelisted in pythonanywhere.com](https://www.pythonanywhere.com/forums/topic/31602/) and you can try to use one of the `api_proxy`:

```
'api_proxy': 'http://proxy.server:3128'
or
'api_proxy': 'https://proxy.server:3128'

**Comment by Maxiron** [comment] 2022-08-16 05:05
> The 'api.cloudinary.com:443' has now been [whitelisted in pythonanywhere.com](https://www.pythonanywhere.com/forums/topic/31602/) and you can try to use one of the `api_proxy`:
> 
> ```
> 'api_proxy': 'http://proxy.server:3128'
> or
> 'api_proxy': 'https://proxy.server:3128'
> ```

Thank you 
The major issue was that I called the cloudinary.uploader and .api before it instead of after

**Comment by epasos573** [comment] 2022-08-16 05:17
Glad to know it is now working for your application! And it is necessary to [initialize the Cloudinary object before importing the other packages](https://cloudinary.com/documentation/django_integration#configuration:~:text=%2C%0A%20%20secure%20%3D%20true%0A)-,Note,-You%20must%20set):

```
import cloudinary

cloudinary.config(
    cloud_name = "xxxx",
    api_key = "xxxxxxxxxxxx",
    api_secret = "xxxxxxxxxxx",
    api_proxy = "https://proxy.server:3128"
)

import cloudinary.uploader
import cloudinary.api
```

**Comment by DevAnbu2k4** [comment] 2023-01-16 16:07
> The `api_proxy` can be declared either at the OS env (e.g., `export CLOUDINARY_URL=cloudinary://API_KEY:API_SECRET@cloud_name?api_proxy=http://x.x.x.x:8080`) or when initializing the Cloudinary object (i.e., setting configuration parameters globally in your Python application):
> 
> ```
> CLOUDINARY = {
>       'cloud_name': 'CLOUD-NAME',  
>       'api_key': 'xx',  
>       'api_secret': 'xx',
>       'api_proxy': 'http://x.x.x.x:8080'
> }
> ```
> 
> 

Where will be the api_proxy found

**Comment by tommyg-cld** [comment] 2023-01-16 16:36
@DevAnbu2k4 i'm not sure I follow, if you're referring to the `api_proxy` value then this is something you will need to provide. This will be the the URL of a proxy server in your environment for routing all Cloudinary API calls. More here: https://cloudinary.com/documentation/cloudinary_sdks#configuration_parameters

**Comment by SambhramMathad13** [comment] 2024-03-17 15:18
Thank you all

**Comment by ValentinKardzhaliev** [comment] 2024-04-12 15:57
I still don't get how to get the api_proxy. Any help?

**Comment by dannyv-cloudinary** [comment] 2024-04-13 09:11
Hey @ValentinKardzhaliev. The proxy is something you set, rather than get. To do so, you just need to specify the api_proxy when configuring your Cloudinary object. Something like this:

```
cloudinary.config( 
  cloud_name = "sample", 
  api_key = "874837483274837", 
  api_secret = "a676b67565c6767a6767d6767f676fe1",
  api_proxy = "your_proxy_here"
  secure = True
)
```

For more information, please see https://cloudinary.com/documentation/django_integration#setting_configuration_parameters_globally and https://cloudinary.com/documentation/cloudinary_sdks#configuration_parameters

**Comment by atdcloud** [comment] 2024-04-15 21:58
@ValentinKardzhaliev, this is a configuration feature on Cloudinary python SDK.  I'm not sure if pythonanywhere is applicable here.  We advice you inquire with pythonanywhere documentation.
