### ISSUE TITLE
transformation in django upon upload not working

### ISSUE THREAD

**Issue by bukowa** [cloudinary/pycloudinary#190] opened 2019-03-25 16:44 UTC
I am using your example django project, this is what i added (copied from docs):
But image is not transformed after uploading with direct upload. Why? It works normal with server-side upload using same 'options'...

````python
class PhotoDirectForm(PhotoForm):
    image = CloudinaryJsFileField(
        attrs={'style': "margin-top: 30px"},
        options={
            'tags': "directly_uploaded",
            'crop': 'limit', 'width': 1000, 'height': 1000,
            'eager': [{'crop': 'fill', 'width': 150, 'height': 100}]
        })
````

**Comment by idobarnoam** [comment] 2019-03-27 10:08
@bukowa could you share additional details regarding the use case?
What are the python, django versions you are using
How are you performing the upload?
Where was this added?

**Comment by ivanvenosdel** [comment] 2019-07-17 12:38
I have the same problem and also doesn't seem to apply the tags. Python3.6 and Django 1.11.

**Comment by ivanvenosdel** [comment] 2019-07-17 12:45
As for additional direct uploading options, that is also in the [cloudinary docs](https://cloudinary.com/documentation/django_image_and_video_upload#additional_direct_uploading_options) but, as stated, the options don't seem to apply.

**Comment by idobarnoam** [comment] 2019-07-28 11:34
Thanks, @ivanvenosdel.

We confirmed this n versions 1.11.

We have opened a request with our dev team to look into this.

We would update this thread with any insights when they occur.

**Comment by ivanvenosdel** [comment] 2019-07-30 21:16
@idobarnoam If it helps, I have done extensive debugging trying to figure out a work around and it seems like the options get lost after the point where they are passed to CloudinaryInput widget. I think this is because when render is called on that widget the options in self.attrs are not merged into the local attrs variable (and therefore ignored).

**Comment by bukowa** [comment] 2019-07-31 00:36
I were using 2.x

**Comment by idobarnoam** [comment] 2019-07-31 09:28
@ivanvenosdel Thanks for investigation - it helps!
@bukowa Thanks for the additional information.

We are looking into this and when there are any new insights we would update the thread.

**Closed** 2019-07-31 11:43 UTC
Labels: question

**Comment by ivanvenosdel** [comment] 2019-08-14 11:59
Works for me in Django 1.11x.

**Comment by idobarnoam** [comment] 2019-08-14 12:36
Thanks for confirming @ivanvenosdel!
