### ISSUE TITLE
error when importing cloudinary package

### ISSUE THREAD

**Issue by asimkievich** [cloudinary/pycloudinary#92] opened 2017-03-24 02:54 UTC
I am getting the following error

    import cloudinary

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python2.7/dist-packages/cloudinary/__init__.py", line 6, in <module>
         from six import python_2_unicode_compatible
    ImportError: cannot import name python_2_unicode_compatible

I tried updating the six version, not working.

**Comment by taragano** [comment] 2017-03-24 18:53
Can you please try to run the following and see if it's working for you?

```
pip install urllib3 --upgrade
pip install six --upgrade
```

**Comment by amit-bg** [comment] 2017-08-03 10:15
I tried both and nothing works.
Ubuntu 14.04.5 LTS, python 2.7.6

**Comment by MaorGariv** [comment] 2017-08-08 12:13
Hi @amit-bg,

Sorry for the delayed response.

Can you please share steps to reproduce for us to further investigating (Code used and error stacktrace)?
 
Thanks,
Maor

**Comment by amit-bg** [comment] 2017-08-10 12:33
Hey @MaorGariv,
This is what I get:

$ python
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cloudinary
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/cloudinary/__init__.py", line 13, in <module>
    from six import python_2_unicode_compatible
ImportError: cannot import name python_2_unicode_compatible

**Comment by MaorGariv** [comment] 2017-08-13 09:03
Hi @amit-bg,

Maybe it's an issue of older versions of Django/six.
Can you please upgrade them to the latest version and see if it helps?

Keep me posted.

Thanks,
Maor

**Comment by taragano** [comment] 2017-09-29 20:28
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.

**Closed by taragano** 2017-09-29 20:28 UTC
Labels: question
