### ISSUE TITLE
Wrong public_id in database after direct browser upload

### ISSUE THREAD

**Issue by tim1234567** [cloudinary/pycloudinary#50] opened 2015-04-12 08:13 UTC
After upgrading to v.1.1 plugin saves to the database a new format of the ```public_id```: ```image/upload/v1428825384/ok9wh8hw4yspmjjlruhu.jpg```. Previously the same code was saving ```public_id``` like this — ```v1428525785/gcfnujctdt9i0xephuzk.jpg```.

It causes further errors in template tags. For example, 
```{% cloudinary_url photo.image resource_type="image" %}```
now generates following url:
```
http://res.cloudinary.com/abcdefghi/image/upload/v1/image/upload/v1428825384/ok9wh8hw4yspmjjlruhu.jpg
```

**Comment by TalLevAmi** [comment] 2015-04-12 08:31
We cannot seem to reproduce this issue. Can you share which version of django are you using? Also, how is image defined in the model?

**Comment by tim1234567** [comment] 2015-04-12 08:33
Also attached a screenshot from debugger (look at photo_instance.image object). Hope would be useful.

![screen shot 2015-04-12 at 11 28 30](https://cloud.githubusercontent.com/assets/11811583/7104898/2f881118-e107-11e4-90ee-a2d21b72b381.png)

**Comment by tim1234567** [comment] 2015-04-12 08:35
Django v.1.7.7

Image model:
```
class SpacePhoto(models.Model):
    image = CloudinaryField('image')
    space = models.ForeignKey(Space, related_name='photos')
    is_deleted = models.BooleanField(default=False)
```

**Comment by TalLevAmi** [comment] 2015-04-12 08:37
This looks correctly parsed. Was this saved using the new DB format? 
Also, is the issue present in newly uploaded images or with objects retrieved from the database?

**Comment by tim1234567** [comment] 2015-04-12 08:44
> Was this saved using the new DB format? 
Seems, I don't know what format do you mean :-). Could you provide more details?

> is the issue present in newly uploaded images or with objects retrieved from the database?
The issue presents in newly uploaded images retrieved from the database. E.g. before submitting it to the server/database, I display it in the browser and all works fine. The issue appears after a page reload.

**Comment by tim1234567** [comment] 2015-04-12 08:59
By the way, we can talk via Skype/TeamViewer if it helps you.

**Comment by TalLevAmi** [comment] 2015-04-12 09:03
Can you please try to run photo.image.build_url() from the django shell?

**Comment by TalLevAmi** [comment] 2015-04-12 09:06
DB format change - I meant v1428525785/gcfnujctdt9i0xephuzk.jpg vs image/upload/v1428825384/ok9wh8hw4yspmjjlruhu.jpg

Looks like the screenshot you sent is from before saving the model to the database.

**Comment by tim1234567** [comment] 2015-04-12 09:10
Tried to run build_url() from a view
```
    list_of_photos = target_space.photos.filter(is_deleted=False)
    import sys
    for photo in list_of_photos:
        print(photo.image.build_url(), file=sys.stderr)
```

Output:
```
Exception Type:	AttributeError
Exception Value:	'str' object has no attribute 'build_url'
```

**Comment by tim1234567** [comment] 2015-04-12 09:25
The same error occurs after replacing:
```
print(photo.image.build_url(), file=sys.stderr)
```

on this:
```
print(cloudinary.CloudinaryImage(photo.image).build_url(), file=sys.stderr)
```

**Comment by tim1234567** [comment] 2015-04-12 10:08
This code is being executed on the server after direct (browser) upload:
```
        photo_instance = SpacePhoto(space=space)
        form = PhotoDirectUploadForm(request.POST, instance=photo_instance)
        if form.is_valid():
            form.save()
            ret = dict(id=photo_instance.id, public_id=photo_instance.image.public_id)
        else:
            ret = dict(error={'id': 'FORM_VALIDATION_ERRORS', 'value': form.errors})
```

**Comment by TalLevAmi** [comment] 2015-04-12 11:05
The issue here is that photo.image is a str and not a CloudinaryResource, which is what CloudinaryField should have returned. We are trying to understand why this is happening in your case.

**Comment by tim1234567** [comment] 2015-04-12 11:20
I use python 3. Probably that could help — http://stackoverflow.com/questions/14078755/django-custom-model-fields-to-python-not-called

**Comment by tim1234567** [comment] 2015-04-12 11:32
Yep, it worked for me!

In cloudinary/models.py replace:
```
15. class CloudinaryField(models.Field):
```

with this line:
```
15. class CloudinaryField(models.Field, metaclass=models.SubfieldBase):
```

**Comment by TalLevAmi** [comment] 2015-04-12 11:33
Great catch. Thanks!

**Comment by tim1234567** [comment] 2015-04-12 14:12
You're the best, guys :+1: ! Didn't expected that anyone works on sundays.

**Comment by tim1234567** [comment] 2015-04-12 14:20
Do you know when this patch will be available via pip?

**Comment by TalLevAmi** [comment] 2015-04-12 17:53
We plan to release a new version in the next few days after some more internal testing.

**Comment by taragano** [comment] 2015-11-23 15:24
Closing this issue due to the time elapsed.
Please feel free to contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Closed by taragano** 2015-11-23 15:24 UTC
Labels: bug
