### ISSUE TITLE
Cloudinary Library Doesn't Have Uploader

### ISSUE THREAD

**Issue by kyeer** [cloudinary/pycloudinary#95] opened 2017-04-05 01:09 UTC
Just doing a basic upload does not work and getting "No module named cloudinary.uploader" error. I tried this in my python IDE, Jupyter and Command Line and got issues with all of them.

**Comment by SummerStorm** [comment] 2017-04-09 06:04
Same thing here. I'm using Python 3.5.2 with cloudinary 1.7.0.

**Comment by MaorGariv** [comment] 2017-04-09 15:57
Hi @kyeer and @SummerStorm ,

Can you share some more information (full error stack, the code used, etc.)?
I couldn't reproduce the issue..

Thanks

**Comment by SummerStorm** [comment] 2017-04-10 06:35
I'm on Ubuntu 16.04 LTS, using Python 3.5.2 and pip 8.1.1.

I did `pip3 install cloudinary` which successfully installed cloudinary 1.7.0.

I then tried to run the following script (first lines of `samples/basic/basic.py`):
```
#!/usr/bin/env python
import os, sys

from cloudinary.uploader import upload
from cloudinary.utils import cloudinary_url
from cloudinary.api import delete_resources_by_tag, resources_by_tag
```
which failed with the following error:

```
Traceback (most recent call last):
  File "basic.py", line 4, in <module>
    from cloudinary.uploader import upload
  File "/XXX/XXX/XXX/cloudinary.py", line 3, in <module>
    from cloudinary.uploader import upload
ImportError: No module named 'cloudinary.uploader'; 'cloudinary' is not a package
```

**Comment by MaorGariv** [comment] 2017-04-10 22:12
Hi, thanks for the additional input.
Please try to rename `cloudinary.py` to something else since that confuses Python. Also, delete `cloudinary.pyc` if exists.

**Comment by SummerStorm** [comment] 2017-04-11 02:47
Thanks! Solved.

**Comment by MaorGariv** [comment] 2017-05-03 14:59
Hi @kyeer,
I'm closing this issue for now due to the elapsed time, but feel free to reach out if you're still experiencing any problems.

**Closed by MaorGariv** 2017-05-03 14:59 UTC
