### ISSUE TITLE
Module does not have attribute 'uploader/upload'.

### ISSUE THREAD

**Issue by Milap7** [cloudinary/pycloudinary#77] opened 2016-10-17 10:53 UTC
Having trouble using upload method. I am using RaspberryPi and am getting this error. I have used `pip install cloudinary`.

**Comment by roeeba** [comment] 2016-11-20 10:21
Hi @Milap7, can you please share some more details about the issue you're facing? please share the code you're using for the upload and the full error stacktrace, so we can better understand the issue. Thanks!

**Comment by roeeba** [comment] 2017-01-08 13:14
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Closed by roeeba** 2017-01-08 13:14 UTC

**Comment by olitomas** [comment] 2017-03-17 13:16
I cant get this working an i suspect the issue is related to this one.

I have a virtual environment and installed cloudinary ("pip install cloudinary") and have double checked that I am inside of my virtualenv and that the package has been installed.

Then i created a test.py with this code:

`
import cloudinary
import cloudinary.uploader
import cloudinary.api

cloudinary.config( 
  cloud_name = "myspecialname", 
  api_key = "myapikey", 
  api_secret = "mysecret" 
)

def test():
	print 'hello test'
`

But when i try to run the file I receive this error: "No module named uploader"

**Comment by MaorGariv** [comment] 2017-03-20 09:15
Hi @olitomas,

If you're experiencing the same issue as #90, please try to add 'cloudinary' to your installed apps.

Let me know how it goes.
