### ISSUE TITLE
delete_resources returns "Missing required parameter - public_ids"

### ISSUE THREAD

**Issue by skadavan** [cloudinary/pycloudinary#76] opened 2016-09-09 14:02 UTC
delete_resources api is not able to delete (http://cloudinary.com/documentation/admin_api#delete_uploaded_images_by_public_ids)

Usage:
res = cloudinary.api.delete_resources(['test-img'])

Result:
Exception is thrown with this message: "Missing required parameter - public_ids'. The result is same if executed with valid/invalid public_ids

**Comment by roeeba** [comment] 2016-09-11 12:46
Hi @skadavan, I wasn't able to reproduce the issue on my side. Can you please make sure you are using the latest library version and try again? if it's still not working for you, please let me know your cloud name and the timeframe in which you have failed to delete so I can check your logs. Thanks.

**Comment by skadavan** [comment] 2016-09-13 14:50
Hi @roeeba, I am using version 1.4.0 of Cloudinary.
Tried again now and the same issue occurs. Other APIs, say update() is working fine.

Can you send me your office email - I will send the cloudname details in it.

**Comment by roeeba** [comment] 2016-09-14 13:07
@skadavan, I want to check the logs to see where the issue is, can you please let me know the cloud-name you are working on? if you want to keep it private, please feel free to share the details via a [support ticket](https://support.cloudinary.com/hc/en-us/requests/new). Thanks

**Comment by skadavan** [comment] 2016-09-14 13:24
I have submitted the ticket #35627. Thanks!

**Comment by roeeba** [comment] 2016-09-14 13:49
Thanks @skadavan. We'll reply shortly.

**Comment by roeeba** [comment] 2016-09-22 12:05
Summarising the issue - Currently our Python library doesn't work well on Google Apps dev server/GAE with Python 2.7. Our dev team is aware of this issue. Currently no ETA to share.

**Comment by roeeba** [comment] 2020-03-23 08:03
This issue was fixed on later versions of the library.

**Closed by roeeba** 2020-03-23 08:03 UTC
Labels: enhancement
